name: Markdown List Linter
description: Lint markdown lists to warn when list items are not alphabetically ordered
author: Clyde D'Souza
branding:
  color: green
  icon: check-circle

inputs:
  file:
    description: The full file path to the markdown file.
    required: true

  fail-on-error:
    description: >
      Set this to false so that the action doesn't cause the workflow to fail if it spots lint issues.
      When set to false, it only produces a warning. 
    default: true

outputs:
  name:
    description: Name of the package.

  summary:
    description: A short summary produced by the markdown list linter.

  errors:
    description: The error object produced by the markdown list linter.

runs:
  using: node16
  main: action.js