name: Markdown List Linter
description: Lint markdown lists to warn when list items are not alphabetically ordered
author: Clyde D'Souza
branding:
  color: green
  icon: check-circle

inputs:
  file:
    description: The full file path to the markdown file.
    required: true

outputs:
  name:
    description: Name of the package.

  summary:
    description: A short summary produced by the markdown list linter.

  errors:
    description: The error object produced by the markdown list linter.

runs:
  using: node18
  main: action.js