name: Markdown List Linter
description: Lint markdown lists to warn when list items are not alphabetically ordered
author: Clyde D'Souza
branding:
  color: green
  icon: check-circle

inputs:
  file:
    description: The full file path to the markdown file
    required: true

outputs:
  id:
    description: >
      The identifier of the published package.
      If a release was published, format is `${name}@${version}.
      If no release occurred, will be an empty string.

  type:
    description: >
      The type of version change that occurred on the published tag.
      If release was an upgrade, will be a semver release type ("major", "minor", ...).
      If the published tag had no previous version, will be "initial".
      If version was change was not an upgrade, will be "different".
      If no release occurred, will be an empty string.

  name:
    description: Name of the package.

  version:
    description: Version of the package.

  old-version:
    description: >
      The previous version on the distribution tag.
      If there was no previous version on the tag, will be an empty string.

  registry:
    description: The registry used for version checking and publishing.

  tag:
    description: The distribution tag used for version checking and publishing.

  access:
    description: >
      The package access setting used.
      If configured by the action or package.json, will be "public" or "protected".
      If not configured for a non-scoped package, will be "public".
      If not configured for a scoped package, will be "default".

runs:
  using: node18
  main: action.js