name: "Build and commit action"

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - action.js
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
      - action.js

jobs:
  build_publish:
    name: Build and publish npm package
    runs-on: ubuntu-latest    
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    
    - name: Install dependencies
      run: npm ci

    - name: Build action
      run: npm run build
    
    - name: Commit the compiled action file
      uses: actions-x/commit@v6
      if: |
        success() &&
        github.ref == 'refs/heads/main'
      with:
        branch: main
        files: action.js
    
    - name: Upload compiled action file as an artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./website/build